name: "Krypto"
description: "Create GitHub issues from comments programmatically"
inputs:
  dir:
    description: "Directory to check for TODOs"
    required: false
    default: "."
run:
  using: "docker"
  image: "Dockerfile"
