[tool.poetry]
name = "krypto"
version = "0.1.0"
description = "A python API that creates issues in your repos based on TODO: comments in your code"
authors = ["antoniouaa <antoniouaa@hotmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"
click = "^8.0.1"
tomli = "^1.0.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.6b0"
taskipy = "^1.8.1"
pytest-cov = "^2.12.1"
coveralls = "^3.1.0"
responses = "^0.13.3"

[tool.poetry.scripts]
krypto = "krypto:cli"

[tool.taskipy.tasks]
launch = { cmd = "python -m krypto", help = "Create TODOs from your project"}
test = { cmd = "pytest -vvv --cov=krypto", help = "Run all the tests"}

# Example config
# [tool.krypto]
# prefix = "TODO"
# include = "tests"
# attach-issue = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
