import pathlib

import pytest

from krypto.todo import Todo


username = "antoniouaa"
repository = "krypto"


todo_from_json = [
    {
        "title": "This is a sample title",
        "body": "this is the body of the todo",
        "labels": ["Enhancement", "Bug"],
    },
    {
        "title": "This is a second sample title",
        "body": "this is the body of the todo",
        "labels": ["Enhancement", "Bug"],
    },
    {
        "title": "This is a final sample title",
        "body": "this is the body of the todo",
        "labels": ["Enhancement", "Bug"],
    },
]


@pytest.fixture(scope="function")
def sample_todo():
    info = {
        "title": "This is a sample title",
        "body": "this is the body of the todo",
        "labels": ["Enhancement", "Bug"],
        "line_no": 10,
        "origin": pathlib.Path("."),
    }
    return Todo(**info)


@pytest.fixture(scope="function")
def sample_request_body_empty_issue_body():
    issue_body = "Autogenerated by [antoniouaa/krypto](https://github.com/antoniouaa/krypto)\n\nLine: 1 in [`tests/conftest.py`](https://github.com/antoniouaa/krypto/blob/master/tests/conftest.py#L1)"
    return {"title": "This is a sample title", "body": issue_body, "labels": ["Bug"]}
