import responses

from krypto.github import prepare_body, get_basename, get_issue
from tests.conftest import username, repository, todo_from_json


def test_request_body_all_fields(sample_todo):
    body = prepare_body(sample_todo, username=username, repo_name=repository)
    assert isinstance(body, dict)
    assert body["title"] == sample_todo.title
    assert body["labels"] == sample_todo.labels
    assert str(sample_todo.origin).replace("\\", "/") in body["body"]


def test_request_body_no_body(sample_todo):
    sample_todo.body = ""
    body = prepare_body(sample_todo, username=username, repo_name=repository)
    assert isinstance(body, dict)
    assert body["title"] == sample_todo.title
    assert body["labels"] == sample_todo.labels
    assert (
        "Autogenerated by [antoniouaa/krypto](https://github.com/antoniouaa/krypto)"
        in body["body"]
    )


def test_get_issue():
    issue = get_issue(todo_from_json, "This is a final sample title")

    assert issue["title"] == "This is a final sample title"


def test_basename():
    username, repo_name = get_basename()

    assert username == "antoniouaa"
    assert repo_name == "krypto"
