from krypto.github import prepare_body

from tests.conftest import username, repository


def test_request_body_all_fields(sample_todo):
    body = prepare_body(sample_todo, username=username, repo_name=repository)
    assert isinstance(body, dict)
    assert body["title"] == sample_todo.title
    assert body["labels"] == sample_todo.labels
    assert str(sample_todo.origin).replace("\\", "/") in body["body"]


def test_request_body_no_body(sample_todo):
    sample_todo.body = ""
    body = prepare_body(sample_todo, username=username, repo_name=repository)
    assert isinstance(body, dict)
    assert body["title"] == sample_todo.title
    assert body["labels"] == sample_todo.labels
    assert (
        "Autogenerated by [antoniouaa/krypto](https://github.com/antoniouaa/krypto)"
        in body["body"]
    )
