name: Krypto

on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate issues
        id: launch
        uses: antoniouaa/krypto@action
        with:
          dir: "."
        env:
          TOKEN_GITHUB: ${{secrets.GITHUB_TOKEN}}

      - name: Output quantity
        run: |
          echo "${{steps.launch.outputs.quantity}} TODOs created"
