name: Krypto

on: [push]

jobs:
  krypto:
    runs-on: ubuntu-18.04
    name: Run krypto
    steps:
      - name: Checkout krypto
        id: checkout
        uses: antoniouaa/krypto
        with:
          dir: "."
