name: Krypto

on: [push]

jobs:
  krypto:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout krypto
        uses: antoniouaa/krypto@master
        with:
          directory: "."
        env:
          TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
