name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup PDM
      - uses: actions/checkout@v4
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install

      - name: Run the tests
        run: |
          pdm run task test
          pdm run coveralls --service=github
        env:
          KRYPTO_TOKEN: ${{ secrets.KRYPTO_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
