name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.1.6

      - name: Install dependencies
        run: |
          poetry install
          poetry -V
          poetry run pytest -V

      - name: Run the tests
        run: |
          poetry run task test
          poetry run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
