name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install python 3.11
        uses: actions/setup-python@v5
        with:
            python-version: 3.11

      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install

      - name: Run the tests
        run: |
            pdm run task test
            pdm run coveralls --service=github
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            KRYPTO_TOKEN: ${{ secrets.KRYPTO_TOKEN }}
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
