name: Run testcases

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install poetry
        uses: nok/install-poetry@v1.1.6

      - name: Install dependencies
        run: poetry install

      - name: Run the tests
        run: poetry run task test -vvv
